// Generated by CoffeeScript 2.7.0
var getFullPath;

getFullPath = (directory) => {
  var p, path;
  path = require('path');
  p = path.resolve(process.cwd(), directory);
  return (name) => {
    return path.resolve(p, name);
  };
};

module.exports = {getFullPath};

//# sourceMappingURL=common-node.js.map
