// Generated by CoffeeScript 2.5.1
var getFullPath;

getFullPath = (directory) => {
  var p, path;
  path = require('path');
  p = path.join(process.cwd(), directory);
  return (name) => {
    return path.join(p, name);
  };
};

module.exports = {getFullPath};

//# sourceMappingURL=common-node.js.map
